### PR TITLE
WIP: Allow custom tags while parsing YAML

### PR DESCRIPTION
**Pull request by aa8y**
Definitely not the most efficient way to do it but I just wanted to convey my intentions. If you have feedback on how to do it better, that would be great.

### CODE REVIEW

**Comment by jcazevedo** [comment]
Thanks for your PR!

I'm not very familiar with the usage of custom tags in YAML, so I might need some time to review this properly and give feedback on the implementation. I'll try to do it over the weekend.

**Comment by aa8y** [comment]
@jcazevedo I've checked in more code, which I think is a better way to support custom tags. This is still inefficient though. I know how I would fix it, but that's making almost all tests to fail and I don't understand why. I've left more information in TODOs in the file `Parser.scala`.

**Comment by jcazevedo** [comment]
> I know how I would fix it, but that's making almost all tests to fail and I don't understand why.

If the build is only failing for Scala 2.10, don't worry. The reflection API we're using is not thread-safe in Scala 2.10 and that got exposed when we updated the `specs2` version in #16.

**Comment by aa8y** [comment]
I was indeed wondering why Travis failed it when it ran fine locally on my machine. But the tests are passing (for other versions) because I creating new objects every time we parse a YAML string. Look at the TODOs and you'll get the context. That is what I need help with.

**Comment by jcazevedo** [comment]
My understanding of tags in the YAML spec is that they give hints on the type of a given node. Tags available in the specs' [repository](http://yaml.org/spec/1.2/spec.html#tag/repository/) are already supported, but it seems to me that more fundamental changes are needed if we want to support custom tags properly. SnakeYAML supports them by allowing the definition of custom `Constructors` with specific instances of `Construct` for different tags, but then it returns `Object` as a result of the parsing process. 

I don't want to have the `parseYaml` method returning `AnyRef`, as we would lose a lot of the type safety and defeat the purpose of the `YamlFormats`. One of the goals of MoultingYAML is to provide a simple  model of the YAML language, and I would really prefer the value to be returned by `parseYaml` to be application-agnostic.

That being said, I'm not against adding the tag information in the document to `YamlValue`, as that can help `YamlFormats` to make better decisions when reading from them.

Can you elaborate on what your use case for custom tags is?

**Comment by aa8y** [comment]
So we have a Ruby on Rails based application which converts Ruby objects to YAML. Sadly it adds non-standard tags to the YAML string it returns (eg. `!map:HashWithIndifferentAccess`, `!ruby/hash:ActiveSupport::HashWithIndifferentAccess`). We have been using SnakeYAML with a custom constructor which helps it interpret these tags. I wanted to add the same support to MoultingYaml before we can start using it.

And maybe I misunderstood what you were saying about SnakeYAML returning an `Object` for custom tags, but the changes I have in my PR should return valid `YamlValue` objects. For example, this is how a valid YAML with valid tags works.

```
scala> import net.jcazevedo.moultingyaml.defaultParser._
import net.jcazevedo.moultingyaml.defaultParser._

scala> "- !!str Foo\n- !!int 123\n- !!float 123\n- !!bool false".parseYaml
res0: net.jcazevedo.moultingyaml.YamlValue = YamlArray(Vector(YamlString(Foo), YamlNumber(123), YamlNumber(123.0), YamlBoolean(false)))
```

A YAML with invalid tag `!someStringTag` would throw an execption.
`org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for !someStringTag; exception=Invalid tag: !someStringTag`

However, we should be able to add support for custom tags like this.

```
scala> import net.jcazevedo.moultingyaml.Parser
import net.jcazevedo.moultingyaml.Parser

scala> val parser = new Parser(Map("!someBoolTag" -> "boolean", "!someFloatTag" -> "float", "!someIntTag" -> "int", "!someStringTag" -> "string"))
parser: net.jcazevedo.moultingyaml.Parser = net.jcazevedo.moultingyaml.Parser@15f8d7b0

scala> import parser._
import parser._

scala> "- !someStringTag Foo\n- !someIntTag 123\n- !someFloatTag 123\n- !someBoolTag false".parseYaml
res0: net.jcazevedo.moultingyaml.YamlValue = YamlArray(Vector(YamlString(Foo), YamlNumber(123), YamlNumber(123.0), YamlBoolean(false)))
```

So you see it doesn't return an object of type `AnyRef`.

**Comment by jcazevedo** [comment]
> A YAML with invalid tag !someStringTag would throw an execption.
> org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for !someStringTag; exception=Invalid tag: !someStringTag
> 
> However, we should be able to add support for custom tags like this.

The thing is SnakeYAML allows its `Construct` to build any java object from a node (see [Construct.java](https://bitbucket.org/asomov/snakeyaml/src/92dcdb2b67d5a1c9c4bf1c052a60ce46a7d0bb80/src/main/java/org/yaml/snakeyaml/constructor/Construct.java?at=default&fileviewer=file-view-default#Construct.java-37)). I don't want to allow `parseYaml` that level of flexibility, for the reasons I enumerated before.

However, I think we should allow parsing YAML documents with custom tags. The most application-agnostic way to do that would be to allow any tag in the document, and store that tag information in `YamlValue`, so that `YamlProtocols` can then use it.

You suggested defining a mapping between custom tags and tags available in the specs' repository (more generically, a `YamlValue => YamlValue` transformation for custom tags). I have mixed feelings about that approach as I don't want the `parseYaml` method to be application-specific (that's for `YamlProtocols`).

Do you think allowing any custom tag and storing that information in `YamlValue` solves your use case?

**Comment by aa8y** [comment]
Firstly, I apologize for the late response. So you mean to say that we would let all tags (weather valid  or not) and then the tag information will be in `YamlValue`. And these tags would be dealt with in one of the formats (like `BasicFormats`)? If this is what you were thinking, it should work for my use case as long as I get to specify non-standard tags and their types. I don't really have a preference on how it's implemented.

However, I would be interested in knowing how you would like to start the implementation for this. I am pretty sure snake-yaml would throw an exception when it encounters invalid tags with its' default constructor.

**Comment by aa8y** [comment]
@jcazevedo I am still trying to understand why you think my implementation would behave any different than the current implementation of `moultingyaml`. I would like to explain my train of thought why I think it behave exactly the same as right now and there is no `YamlValue => YamlValue` mapping going on. However, if your plan is to change the implementation of `moultingyaml` itself such that a `YamlValue` object would always have a tag whether it's a standard tag or custom, please ignore all this.

From what I see, this is how it goes. `Yaml.load()` calls `Yaml.loadFromReader()` which then calls `BaseConstructor.getSingleData()` whose return type is `Object`; but ideally it should return an object of appropriate type which is casted to `Object` before returning. If we look at `getSingleData()`, it calls `Composer.composeDocument()` which returns a node. With this node it calls `BaseConstructor.constructDocument()` which then calls `BaseConstructor.constructObject()`. `constructObject()` tries to get the appropriate constructor by calling `BaseConstructor.getConstructor()` which then returns the appropriate `Constructor` object from `BaseConstructor.yamlConstructors` hash map using tag of the node passed to `constructObject()` as the key.

Now, if it's a valid tag (which all standard tags are) then you get a valid constructor (all defined in `SafeConstructor`). If it's an invalid tag, we get `null` back. What I did is to add all non-standard tags to constructor mappings, passed to the (new) `Parser` class, to `BaseConstructor. yamlConstructors`. So, when one of the newly added tags are encountered, the appropriate constructor is returned as if it were a standard tag.

So you can see that there is no `YamlValue => YamlValue` mapping happening anywhere and the `YamlValue` is constructed from the object returned by `Yaml.load()` as it was before. Hope this clears things up. If not, please let me know.

**Comment by aa8y** [comment]
@jcazevedo Just wanted to check if my last comment makes sense. Do you have any additional thoughts about it?

**Comment by jcazevedo** [comment]
Sorry for the delay in replying to this.

What I meant by the `YamlValue => YamlValue` mapping is that when you define something like

```scala
new Parser(Map("!someBoolTag" -> "boolean"))
```

you're saying that nodes tagged with `!someBoolTag` should be read as boolean (possibly incurring in a transformation of their "implicit" type).

I've been trying to make MoultingYAML store the tags of nodes in the `YamlValue` representation, so that custom tags can be handled by `YamlProtocol` implementations, but I'm not quite there yet. I hope I can make some progress later today.

**Comment by aa8y** [comment]
If you can get the `YamlValue`s to have tags, I can help with the custom tag implementation. I'll keep this branch in sync with upstream master.

**Comment by jcazevedo** [comment]
I've started working on adding support to tags to the AST in the [`tags` branch](https://github.com/jcazevedo/moultingyaml/tree/tags). Please take into account that things are still quite experimental at this stage (not even all of the tests are passing).

**Comment by aa8y** [comment]
Closing due to inactivity in the project.

**Pull request closed without merging**
