### PR TITLE
Cross-compile for Scala 2.12

### PR DESCRIPTION
**Pull request by OlegIlyenko**
I also updated the dependencies

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
looks like `scoverage` plugin is not updated yet :(

**Comment by ruippeixotog** [comment]
If @jcazevedo agrees with it, you can temporarily change .travis.yml to work [like this](https://github.com/ruippeixotog/akka-testkit-specs2/blob/master/.travis.yml).

**Comment by OlegIlyenko** [comment]
Yeah, I currently struggle to do the same kind of stuff in other project of mine (without much success so far :)). I also saw that other libs also did the same (like shapeless).

If I manage to make it work, I will update this PR as well :)

**Comment by OlegIlyenko** [comment]
hmmm... this time around it looks like a race condition in scala 2.10 reflection API (it's not thread-safe in this version, I also saw similar errors before): https://travis-ci.org/jcazevedo/moultingyaml/jobs/173095273#L748

**Comment by jcazevedo** [comment]
I'm going to merge this and attempt to fix the issue with Scala 2.10 build in another PR, so that we don't delay the release of a MoultingYAML version for Scala 2.12.0.

**Comment by jcazevedo** [comment]
Just released v0.3.1 with support for Scala 2.12.0. It's already available at Sonatype OSSRH but it might take a while before it's synced to the central repository.

**Comment by OlegIlyenko** [comment]
Wow, that was fast! thanks a lot!

**Pull request merged**
