### PR TITLE
support scala 2.13

### PR DESCRIPTION
**Pull request by kapkaev**
## Add scala 2.13

- Removed 2.10.x because it conflicts with `specs2-core`(4.5.1  don't have an artifact for 2.10)
- Updates plugins to the lates versions

### CODE REVIEW

**Review by htmldoug — APPROVED** [review]
LGTM.

@jcazevedo, how do you want to handle the README?

**Comment by jcazevedo** [comment]
Thanks for this!

@htmldoug: I'll update the README once I publish a new version.

**Comment by kapkaev** [comment]
Thank you!

**Comment by jcazevedo** [comment]
@kapkaev: Just to let you know that version 0.4.1, with support for Scala 2.13, has been published.

**Pull request merged**
